# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dueDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_field', models.CharField(max_length=25)),
                ('due_date', models.CharField(max_length=35)),
            ],
        ),
    ]
