# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budzetmax',
            name='expenditure_month',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='budzetmax',
            name='expenditure_year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budzetmax',
            name='expenduture_date',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
